name: Update Compose Screenshots

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  update:
    runs-on: macos-latest
    env:
      JAVA_VERSION: '17'
      ANDROID_HOME: /Users/runner/Library/Android/sdk

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true    # required so GITHUB_TOKEN can push

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/gradle.lockfile','**/gradle/libs.versions.toml','**/gradle.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Install / Start emulator
        uses: reactivecircus/android-emulator-runner@v2
        id: emulator
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          avd-name: test
          force-avd-creation: true
          emulator-options: -no-snapshot-save -noaudio -no-boot-anim -no-window
          emulator-boot-timeout: 1200
          disable-animations: true

      - name: Debug: tool versions
        run: |
          java -version || true
          ./gradlew -version || true
          $ANDROID_HOME/platform-tools/adb version || true

      - name: Wait for emulator to boot (robust)
        run: |
          set -euxo pipefail
          ADB="$ANDROID_HOME/platform-tools/adb"
          for i in {1..240}; do
            $ADB devices | grep 'emulator-' && break || sleep 1
          done
          for i in {1..900}; do
            BOOT=$($ADB -s emulator-5554 shell getprop sys.boot_completed 2>/dev/null || echo "")
            if [ "$BOOT" = "1" ]; then
              echo "Boot completed"
              break
            fi
            echo "still booting ($i)..."
            sleep 2
          done
          $ADB -s emulator-5554 shell settings put global window_animation_scale 0.0 || true
          $ADB -s emulator-5554 shell settings put global transition_animation_scale 0.0 || true
          $ADB -s emulator-5554 shell settings put global animator_duration_scale 0.0 || true

      - name: Verify emulator connectivity
        run: |
          $ANDROID_HOME/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
          $ANDROID_HOME/platform-tools/adb devices -l

      - name: Run Gradle — regenerate screenshots
        run: ./gradlew --no-daemon --console=plain updateDebugScreenshotTest
        env:
          ANDROID_SDK_ROOT: $ANDROID_HOME

      - name: Show git status & changed files (debug)
        run: |
          git status --porcelain
          git --no-pager diff --name-only

      - name: Commit & push updated screenshots (if any)
        if: ${{ steps.emulator.outcome == 'success' }}
        run: |
          set -euxo pipefail
          # Only commit known screenshot paths to avoid accidental commits
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage the reference images and test reports that may change
          git add -A app/src/debug/screenshotTest/reference || true
          git add -A app/src/debug/screenshotTest/expected || true
          git add -A app/build/test-results || true
          git add -A app/build/reports || true

          # If there are changes, commit and push them
          if ! git diff --staged --quiet; then
            git commit -m "chore(test): update screenshot references (CI)" || true
            git push origin HEAD:master
          else
            echo "No screenshot changes."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (always for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            app/src/debug/screenshotTest/reference/**
            app/build/reports/**
            app/build/test-results/**
