name: Update Compose Screenshots

on:
  workflow_dispatch:   # run manually from GitHub Actions tab
  push:
    branches:
      - master           # optional: only run on main branch

jobs:
  update:
    runs-on: macos-latest
    env:
      JAVA_VERSION: '17'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Start emulator and regenerate screenshots
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          avd-name: test
          force-avd-creation: true
          emulator-options: -no-snapshot-save -noaudio -no-boot-anim -no-window
          emulator-boot-timeout: 1200
          disable-animations: true
          script: ./gradlew --no-daemon --console=plain updateDebugScreenshotTest
