name: Update Compose Screenshots

on:
  workflow_dispatch:   # run manually from GitHub Actions tab
  push:
    branches:
      - master           # optional: only run on main branch

jobs:
  update:
    runs-on: macos-latest   # macOS gives you faster + stable emulator
    env:
      JAVA_VERSION: '17'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # needed for committing changes back

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Start emulator and regenerate screenshots
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          avd-name: test
          force-avd-creation: true
          emulator-options: -no-snapshot-save -noaudio -no-boot-anim -no-window
          emulator-boot-timeout: 1200
          disable-animations: true
          script: ./gradlew --no-daemon --console=plain updateDebugScreenshotTest

      - name: Commit & Push updated screenshots
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add app/src/debug/screenshotTest/reference
          git commit -m "chore: update screenshot baselines [ci skip]" || echo "No changes to commit"
          git push
