name: Validate Compose Screenshots

on:
  pull_request:
  push:
    branches:
      - "**"    # optional: restrict to branches you want

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/gradle.lockfile', '**/gradle/libs.versions.toml', '**/gradle.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Install Android SDK components
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          emulator-options: "-no-window"
        # The action installs SDK/build-tools needed by AGP. It also accepts licenses.

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run screenshot validation
        # This task fails if validation fails (which is what you want in CI).
        run: ./gradlew --no-daemon --console=plain validateDebugScreenshotTest
